#!/bin/bash

FILE="/etc/passwd"

read -p "Enter a username > " NAME

file_info=$(grep -E "^$NAME:" $FILE)

if [ -n "$file_info" ]; then
	IFS=":" read user pw uid gid name home shell <<< "$file_info"
	echo "User =      '$user'"
	echo "UID =        '$uid'"
	echo "GID =        '$gid'"
	echo "Full Name = '$name'"
	echo "Home Dir. = '$home'"
	echo "Shell =     '$shell'"
else
	echo "No such user '$NAME'" >&2
	exit 1
fi
