#!/bin/bash

read x

if [[ $x =~ ^-?[0-9]+$ ]]; then
	if [ $x -eq 0 ]; then
		echo "It is zero."
		exit
	fi
	if [ $x -lt 0 ]; then
		echo "It is negative."
	else
		echo "It is positive."
	fi
	if [ $((x % 2)) -eq 0 ]; then
		echo "It is even."
	else
		echo "It is odd."
	fi
else
	echo "Not an integer." >&2
fi

exit
